#![allow(dead_code)]
/* automatically generated by rust-bindgen 0.72.1 */

pub const PANEL: i32 = 1;
pub const PANEL_NUMERIC_1: i32 = 2;
pub const PANEL_NUMERIC_2: i32 = 3;
pub const PANEL_RESULT: i32 = 4;
pub const PANEL_QUITBUTTON: i32 = 5;
